// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPnk9_foKk9BzKCGWAvqjKDXW-WLknSDU',
    appId: '1:43814895104:web:5257b9ef40058d5d01e2e5',
    messagingSenderId: '43814895104',
    projectId: 'firebase2-practice',
    authDomain: 'fir-2-practice-296e5.firebaseapp.com',
    storageBucket: 'firebase2-practice.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlVdx2mhZ2PnmYeTiZl6Ev44t-AaZ7EYk',
    appId: '1:43814895104:android:effd15bcc63dd87f01e2e5',
    messagingSenderId: '43814895104',
    projectId: 'firebase2-practice',
    storageBucket: 'firebase2-practice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHJaxv8zNwRGwccMC8Crrg3IBPLEeNpj4',
    appId: '1:43814895104:ios:16420908c721b3ae01e2e5',
    messagingSenderId: '43814895104',
    projectId: 'firebase2-practice',
    storageBucket: 'firebase2-practice.appspot.com',
    iosClientId: '43814895104-d4i68utc1f291adqn127c37b0ri0350j.apps.googleusercontent.com',
    iosBundleId: 'com.gmail.mamimami49192.example.firebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHJaxv8zNwRGwccMC8Crrg3IBPLEeNpj4',
    appId: '1:43814895104:ios:cbdb920155d0d67e01e2e5',
    messagingSenderId: '43814895104',
    projectId: 'firebase2-practice',
    storageBucket: 'firebase2-practice.appspot.com',
    iosClientId: '43814895104-6fjeem3bcbsn4qfsbo9kodf8upjq07o4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase2.RunnerTests',
  );
}
